# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://rtgoodwin.github.io/
baseurl: /
title: Richard Goodwin
author: Richard Goodwin
description: Home on the range
avatar: profile.png
email: richardg@richardgoodwin.com
github: rtgoodwin
twitter: rgoodwin
linkedin: richardgoodwin
google_analytics: XXX
resume: http://rtgoodwin.github.io/cv
